version: '3.5'

services:
  # node_db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: assesment_db
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"


  node_backend: 
    container_name: assessment_venturenox
    image: assessment_venturenox:0.0.7
    build:
      context: .
    ports: 
      - "3000:3000" 
    environment:
      - EXTERNAL_PORT=3000
      - PGDATABASE=assesment_db
      - PGUSER=noorimranrana
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=noorimranrana
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=assesment_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

# volumes:
#   - nps_data: {}



    




